version: '3.9'

services:
  db:
    image: postgres:17
    container_name: pharma_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharma_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Pharma.Recipes.API/Dockerfile
    container_name: pharma_api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=pharma_db;Username=postgres;Password=postgres
      Jwt__Key: "pharma_super_secret_key_2025_very_secure!"
      Jwt__Issuer: "PharmaRecipes"

volumes:
  pgdata:

