version: '3.9'
services:
  db:
    image: postgres:17
    container_name: pharma-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pharma
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Pharma.Recipes.API/Dockerfile
    container_name: pharma-api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=pharma;Username=postgres;Password=1234"
    networks:
      - default

volumes:
  db-data:
